
/* ANY CHANGES TO THIS FILE WILL NOT BE SAVED AND WILL NOT BE COMMITTED */

#define TEXTUAL_BUILT_INSIDE_SANDBOX 0
#define TEXTUAL_BUILT_WITH_SPARKLE_ENABLED 1
#define TEXTUAL_BUILT_WITH_APPCENTER_SDK_ENABLED 1
#define TEXTUAL_BUILT_WITH_SPARKLE_ENABLED 1
#define TEXTUAL_BUILT_WITH_LICENSE_MANAGER 1
#define TEXTUAL_BUILT_WITH_ICLOUD_SUPPORT 0
#define TEXTUAL_BUILT_WITH_ADVANCED_ENCRYPTION 1
#define TEXTUAL_BUILT_FOR_APP_STORE_DISTRIBUTION 0
#define TEXTUAL_BUILT_AS_UNIVERSAL_BINARY 1
